DEBUG = True

SERVER_NAME = '127.0.0.1:5000'

SECRET_KEY = ''

CONFIRMATION_TOKEN_EXPIRATION = 3600

MAIL_SERVER = 'smtp.163.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = 'idatahub@163.com'
MAIL_PASSWORD = ''

MAIL_DEFAULT_SENDER = ('DataHub', 'idatahub@163.com')
